// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main #(
 parameter vcdd52f = 4
) (
 output [7:0] vec885a
);
 localparam p0 = vcdd52f;
 wire [0:7] w1;
 assign vec885a = w1;
 vffc517 #(
  .vc5c8ea(p0)
 ) vbd00fc (
  .va0aeac(w1)
 );
endmodule

//---- Top entity
module vffc517 #(
 parameter vc5c8ea = 0
) (
 output [7:0] va0aeac
);
 localparam p0 = vc5c8ea;
 wire [0:7] w1;
 assign va0aeac = w1;
 vffc517_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 8-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 8-bits generic constant (0-255)
//---------------------------------------------------

module vffc517_v465065 #(
 parameter VALUE = 0
) (
 output [7:0] k
);
 assign k = VALUE;
endmodule
