// Code generated by Icestudio 0.10-rc1

`default_nettype none

//---- Top entity
module main #(
 parameter v9d5646 = 1
) (
 input vclk,
 output [7:0] ve22259
);
 localparam p2 = v9d5646;
 wire [0:7] w0;
 wire w1;
 wire w3;
 wire w4;
 wire w5;
 wire [0:2] w6;
 assign ve22259 = w0;
 assign w4 = vclk;
 assign w5 = vclk;
 assign w5 = w4;
 vfebcfe v4f701d (
  .v9fb85f(w1)
 );
 v40bd2f v1a8e00 (
  .v3dc29f(w3),
  .v6dda25(w4),
  .v603990(w6)
 );
 v710737 v5159e4 (
  .vbfc190(w0),
  .v27dec4(w1),
  .v292458(w6)
 );
 va9a5bc #(
  .vfb06ae(p2)
 ) vf9bfb5 (
  .v2a8434(w3),
  .vac0eb2(w5)
 );
endmodule

//---- Top entity
module vfebcfe (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vfebcfe_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 1
//---------------------------------------------------

module vfebcfe_vb2eccd (
 output q
);
 //-- Constant bit-1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module v40bd2f (
 input v6dda25,
 input v3dc29f,
 output [2:0] v603990
);
 wire w0;
 wire [0:2] w1;
 wire w2;
 wire [0:2] w3;
 wire [0:2] w4;
 assign w0 = v3dc29f;
 assign w2 = v6dda25;
 assign v603990 = w3;
 assign w4 = w3;
 v68040c vd07192 (
  .vccca56(w0),
  .va28445(w1),
  .v6dda25(w2),
  .vd4e7bc(w3)
 );
 v097e2f v95c4ef (
  .v25ecb4(w1),
  .v1efb2a(w4)
 );
endmodule

//---------------------------------------------------
//-- Counter-x03
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Counter-x03: 3-bits counter
//---------------------------------------------------
//---- Top entity
module v68040c (
 input v6dda25,
 input [2:0] va28445,
 input vccca56,
 output [2:0] vd4e7bc
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:2] w4;
 wire [0:2] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w4 = va28445;
 assign vd4e7bc = w5;
 assign w8 = v6dda25;
 assign w9 = v6dda25;
 assign w10 = v6dda25;
 assign w11 = vccca56;
 assign w12 = vccca56;
 assign w13 = vccca56;
 assign w9 = w8;
 assign w10 = w8;
 assign w10 = w9;
 assign w12 = w11;
 assign w13 = w11;
 assign w13 = w12;
 v22cb98 v1ba30c (
  .v27dec4(w0),
  .v4642b6(w2),
  .ve4a668(w9),
  .vd793aa(w12)
 );
 v22cb98 v38f79d (
  .v27dec4(w1),
  .v4642b6(w3),
  .ve4a668(w10),
  .vd793aa(w13)
 );
 v9a2795 v1fdbc1 (
  .v3f8943(w0),
  .v64d863(w1),
  .vdee7c7(w4),
  .vda577d(w6)
 );
 v2b9b8c v9a5c21 (
  .vee8a83(w2),
  .v03aaf0(w3),
  .ve52f8a(w5),
  .vf8041d(w7)
 );
 v22cb98 v009467 (
  .v27dec4(w6),
  .v4642b6(w7),
  .ve4a668(w8),
  .vd793aa(w11)
 );
endmodule

//---------------------------------------------------
//-- Reg-x03
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Reg-x03: 3-bits register
//---------------------------------------------------
//---- Top entity
module v22cb98 #(
 parameter v5462c0 = 0
) (
 input ve4a668,
 input v27dec4,
 input vd793aa,
 output v4642b6
);
 localparam p1 = v5462c0;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w2 = ve4a668;
 assign w3 = v27dec4;
 assign v4642b6 = w5;
 assign w6 = vd793aa;
 assign w5 = w4;
 va40d2f v9ff767 (
  .v030ad0(w0),
  .vb192d0(w3),
  .v27dec4(w4),
  .v2d3366(w6)
 );
 v053dc2 #(
  .v71e305(p1)
 ) v89c757 (
  .vf54559(w0),
  .va4102a(w2),
  .ve8318d(w4)
 );
endmodule

//---------------------------------------------------
//-- 1-bit-reg
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Reg: 1-Bit register
//---------------------------------------------------
//---- Top entity
module va40d2f (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v030ad0 = w0;
 assign w1 = v2d3366;
 assign w2 = v27dec4;
 assign w3 = vb192d0;
 vd0c4e5 v0f3fef (
  .v030ad0(w0),
  .v2d3366(w1),
  .vb192d0(w2),
  .v27dec4(w3)
 );
endmodule

//---------------------------------------------------
//-- MuxF-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels). Fippled version
//---------------------------------------------------
//---- Top entity
module vd0c4e5 (
 input v27dec4,
 input vb192d0,
 input v2d3366,
 output v030ad0
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v030ad0 = w0;
 assign w2 = v2d3366;
 assign w3 = v2d3366;
 assign w6 = v27dec4;
 assign w7 = vb192d0;
 assign w3 = w2;
 v873425 vaaee1f (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w4)
 );
 vba518e v569873 (
  .vcbab45(w1),
  .v3ca442(w2),
  .v0e28cb(w6)
 );
 v3676a0 v1f00ae (
  .v0e28cb(w3),
  .vcbab45(w5)
 );
 vba518e vc8527f (
  .vcbab45(w4),
  .v3ca442(w5),
  .v0e28cb(w7)
 );
endmodule

//---------------------------------------------------
//-- Mux-2-1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 2-to-1 Multplexer (1-bit channels)
//---------------------------------------------------
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module v053dc2 #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v053dc2_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- D Flip-flop (verilog implementation)
//---------------------------------------------------

module v053dc2_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v9a2795 (
 input [2:0] vdee7c7,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:2] w2;
 wire w3;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = vdee7c7;
 assign vda577d = w3;
 v9a2795_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2),
  .o2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus3-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus3-Split-all: Split the 3-bits bus into three wires
//---------------------------------------------------

module v9a2795_v9a2a06 (
 input [2:0] i,
 output o2,
 output o1,
 output o0
);
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v2b9b8c (
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [2:0] ve52f8a
);
 wire w0;
 wire w1;
 wire [0:2] w2;
 wire w3;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign ve52f8a = w2;
 assign w3 = vf8041d;
 v2b9b8c_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2),
  .i2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus3-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus3-Join-all: Joint three wires into a 3-bits Bus
//---------------------------------------------------

module v2b9b8c_v9a2a06 (
 input i2,
 input i1,
 input i0,
 output [2:0] o
);
 assign o = {i2, i1, i0};
 
endmodule
//---- Top entity
module v097e2f #(
 parameter v6c5139 = 1
) (
 input [2:0] v1efb2a,
 output v4642b6,
 output [2:0] v25ecb4
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:2] w2;
 wire [0:2] w3;
 assign v4642b6 = w0;
 assign v25ecb4 = w2;
 assign w3 = v1efb2a;
 v75e539 #(
  .vd73390(p1)
 ) v270985 (
  .v4642b6(w0),
  .v8862b1(w2),
  .v3476f0(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-3bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-3bit: Increment a 3-bits number by one
//---------------------------------------------------
//---- Top entity
module v75e539 #(
 parameter vd73390 = 0
) (
 input [2:0] v3476f0,
 output v4642b6,
 output [2:0] v8862b1
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:2] w2;
 wire [0:2] w3;
 wire [0:2] w4;
 assign v4642b6 = w0;
 assign w3 = v3476f0;
 assign v8862b1 = w4;
 v7b367d #(
  .vc5c8ea(p1)
 ) v4445e2 (
  .vc35126(w2)
 );
 v4898bb vfc2867 (
  .v4642b6(w0),
  .v55e830(w2),
  .v7b6a12(w3),
  .v2507ea(w4)
 );
endmodule

//---------------------------------------------------
//-- AdderK-3bits CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-3bit: Adder of 3-bit operand and 3-bit constant
//---------------------------------------------------
//---- Top entity
module v7b367d #(
 parameter vc5c8ea = 0
) (
 output [2:0] vc35126
);
 localparam p0 = vc5c8ea;
 wire [0:2] w1;
 assign vc35126 = w1;
 v7b367d_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 3-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 3-bits generic constant (0-7)
//---------------------------------------------------

module v7b367d_v465065 #(
 parameter VALUE = 0
) (
 output [2:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v4898bb (
 input [2:0] v55e830,
 input [2:0] v7b6a12,
 output v4642b6,
 output [2:0] v2507ea
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:2] w3;
 wire [0:2] w4;
 wire [0:2] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 assign w3 = v7b6a12;
 assign w4 = v55e830;
 assign v2507ea = w5;
 assign v4642b6 = w8;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w12),
  .v82de4f(w14)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w6),
  .v27dec4(w11),
  .v82de4f(w13)
 );
 v9a2795 v9365c0 (
  .vdee7c7(w3),
  .vda577d(w10),
  .v3f8943(w13),
  .v64d863(w14)
 );
 v9a2795 v90e346 (
  .vdee7c7(w4),
  .vda577d(w9),
  .v3f8943(w11),
  .v64d863(w12)
 );
 v2b9b8c v066958 (
  .vee8a83(w1),
  .v03aaf0(w2),
  .ve52f8a(w5),
  .vf8041d(w7)
 );
 vad119b v5d29b2 (
  .v0ef266(w6),
  .v8e8a67(w7),
  .v4642b6(w8),
  .v27dec4(w9),
  .v82de4f(w10)
 );
endmodule

//---------------------------------------------------
//-- Adder-3bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-3bits: Adder of two operands of 3 bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v710737 (
 input v27dec4,
 input [2:0] v292458,
 output [7:0] vbfc190
);
 wire [0:2] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire [0:7] w10;
 assign w0 = v292458;
 assign w1 = v27dec4;
 assign vbfc190 = w10;
 v359c47 v92c2b6 (
  .v292458(w0),
  .v27dec4(w1),
  .v37b32f(w2),
  .v249c9d(w3),
  .va5e8c8(w4),
  .v5824a9(w5),
  .ve48246(w6),
  .v8b3e73(w7),
  .v030ad0(w8),
  .vd53c9c(w9)
 );
 v3407b9 v3a6ef8 (
  .v7bca47(w2),
  .v9a82b6(w3),
  .v703213(w4),
  .vefa3a9(w5),
  .vd84a57(w6),
  .vf8041d(w7),
  .vee8a83(w8),
  .v03aaf0(w9),
  .va9ac17(w10)
 );
endmodule

//---------------------------------------------------
//-- DeMux-1-8-Bus
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 1-to-8 DeMultplexer (1-bit channels) (Output grouped in a bus)
//---------------------------------------------------
//---- Top entity
module v359c47 (
 input v27dec4,
 input [2:0] v292458,
 output v37b32f,
 output v249c9d,
 output va5e8c8,
 output v5824a9,
 output ve48246,
 output v8b3e73,
 output v030ad0,
 output vd53c9c
);
 wire w0;
 wire w1;
 wire [0:2] w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 assign w2 = v292458;
 assign vd53c9c = w4;
 assign v030ad0 = w5;
 assign v8b3e73 = w7;
 assign ve48246 = w8;
 assign v5824a9 = w9;
 assign va5e8c8 = w10;
 assign v249c9d = w11;
 assign v37b32f = w12;
 assign w21 = v27dec4;
 assign w16 = w15;
 assign w17 = w15;
 assign w17 = w16;
 assign w18 = w15;
 assign w18 = w16;
 assign w18 = w17;
 assign w20 = w19;
 v6307bd v1f4fa3 (
  .v27dec4(w0),
  .vd53c9c(w13),
  .v030ad0(w14),
  .vb192d0(w19)
 );
 v6307bd vaaa5ae (
  .v030ad0(w0),
  .vd53c9c(w1),
  .v27dec4(w21),
  .vb192d0(w22)
 );
 v6307bd va8aa75 (
  .v27dec4(w1),
  .vd53c9c(w3),
  .v030ad0(w6),
  .vb192d0(w20)
 );
 v9a2795 vf694da (
  .vdee7c7(w2),
  .v64d863(w15),
  .v3f8943(w19),
  .vda577d(w22)
 );
 v6307bd v33cddb (
  .v27dec4(w3),
  .vd53c9c(w4),
  .v030ad0(w5),
  .vb192d0(w18)
 );
 v6307bd vc8137f (
  .v27dec4(w6),
  .vd53c9c(w7),
  .v030ad0(w8),
  .vb192d0(w17)
 );
 v6307bd v8c057b (
  .vd53c9c(w9),
  .v030ad0(w10),
  .v27dec4(w13),
  .vb192d0(w16)
 );
 v6307bd v1deec8 (
  .vd53c9c(w11),
  .v030ad0(w12),
  .v27dec4(w14),
  .vb192d0(w15)
 );
endmodule

//---------------------------------------------------
//-- DeMux-1-8
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 1-to-8 DeMultplexer (1-bit channels)
//---------------------------------------------------
//---- Top entity
module v6307bd (
 input v27dec4,
 input vb192d0,
 output v030ad0,
 output vd53c9c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign v030ad0 = w0;
 assign vd53c9c = w1;
 assign w3 = v27dec4;
 assign w4 = v27dec4;
 assign w5 = vb192d0;
 assign w6 = vb192d0;
 assign w4 = w3;
 assign w6 = w5;
 vba518e vb523bf (
  .vcbab45(w0),
  .v0e28cb(w3),
  .v3ca442(w6)
 );
 v3676a0 vde5c93 (
  .vcbab45(w2),
  .v0e28cb(w5)
 );
 vba518e vf65161 (
  .vcbab45(w1),
  .v3ca442(w2),
  .v0e28cb(w4)
 );
endmodule

//---------------------------------------------------
//-- DeMux-1-2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 1-to-2 DeMultplexer (1-bit channels)
//---------------------------------------------------
//---- Top entity
module v3407b9 (
 input v7bca47,
 input v9a82b6,
 input v703213,
 input vefa3a9,
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [7:0] va9ac17
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:7] w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign va9ac17 = w4;
 assign w5 = vefa3a9;
 assign w6 = v703213;
 assign w7 = v9a82b6;
 assign w8 = v7bca47;
 v3407b9_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4),
  .i4(w5),
  .i5(w6),
  .i6(w7),
  .i7(w8)
 );
endmodule

//---------------------------------------------------
//-- Bus8-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus8-Join-all: Join all the wires into a 8-bits Bus
//---------------------------------------------------

module v3407b9_v9a2a06 (
 input i7,
 input i6,
 input i5,
 input i4,
 input i3,
 input i2,
 input i1,
 input i0,
 output [7:0] o
);
 assign o = {i7, i6, i5, i4, i3, i2, i1, i0};
 
endmodule
//---- Top entity
module va9a5bc #(
 parameter vfb06ae = 1
) (
 input vac0eb2,
 output v2a8434
);
 localparam p2 = vfb06ae;
 wire w0;
 wire w1;
 assign v2a8434 = w0;
 assign w1 = vac0eb2;
 va9a5bc_v6cac2f #(
  .SEC(p2)
 ) v6cac2f (
  .o(w0),
  .clk(w1)
 );
endmodule

//---------------------------------------------------
//-- Corazon-tic-Sec
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Corazón de bombeo de tics a con periodo paramétrico de segundos
//---------------------------------------------------

module va9a5bc_v6cac2f #(
 parameter SEC = 0
) (
 input clk,
 output o
);
 //localparam SEC;
 
 //-- Constante para dividir y obtener una frecuencia de 1Hz
 localparam M = 12000000*SEC;
 
 //-- Calcular el numero de bits para almacenar M
 localparam N = $clog2(M);
 
 //-- Cable de reset para el contador
 wire reset;
 
 //-- Registro del divisor
 reg [N-1:0] divcounter;
 
 
 //-- Contador con reset
 always @(posedge clk)
   if (reset)
     divcounter <= 0;
   else
     divcounter <= divcounter + 1;
 
 //-- Comparador que resetea el contador cuando se alcanza el tope
 assign reset = (divcounter == M-1);
 
 //-- La salida es la señal de overflow
 assign o = reset;
 
 
 
 
endmodule
